version: '2'

services:
  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    links:
      - 'mysqldb'
  mysqldb:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Cle340tow

