version: '2'

services:
  mysql:
    image: 'bitnami/mysql:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes 
      - MYSQL_DATABASE=stackerdb
      - MYSQL_ROOT_PASSWORD=password123
    volumes:
      - ./storage/db:/bitnami
    ports:
      - 3306:3306
      
  myapp:
    tty: true
    build: ./5
    image: 'sean7218/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
    ports:
      - 3000:3000
    volumes:
      - ./:/app 








