version: '2'

services:
  express:
    tty: true
    image: 'bitnami/express:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - PORT=7070
      - NODE_ENV=development
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    command: npm run development
    ports:
      - 7070:7070
    volumes:
      - ./express:/app
    
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=stackerdb-instance.c9lwfkditd5a.us-east-2.rds.amazonaws.com
      - DB_USERNAME=seanz
      - DB_DATABASE=stackerdb
      - DB_PASSWORD=Cle340tow
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ~/server:/bitnami

